################################################################
# Docker configuration backend
################################################################
[docker]
watch = true
exposedByDefault = false
