version: "3.4"

services:
  api:
    build:
      context: ./api
    image: acid-challenge-api:latest
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/home/node/app
    command: yarn watch
    ports:
      - 8000:8000

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: build-deps
    image: acid-challenge-app:latest
    # user: node
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    # command: yarn start
